const filepathPrefix = "https://530society.nyc3.digitaloceanspaces.com/AudioQuest"

export const MASK_PATHS_RELATIVE = [
// "/masks/_NHt0ZDTUk1pDKfO.mp4",
// "/masks/_w13XKTTxzbJUjAn.mp4",
// "/masks/1t_J8CtMxSy0FV_B.mp4",
// "/masks/3mTgvzaoas-K41IU.mp4",
// "/masks/4InpuBcmZXDImJ6O.mp4",
// "/masks/9MYXnN7RhURggYrR.mp4",
// "/masks/12_enHs-dsfu53QB.mp4",
// "/masks/29gy33VGl5dTXDDu.mp4",
// "/masks/Bc8BChM2Nvmd_Xk8.mp4",
// "/masks/bvU1yaZwsd0V9DRO.mp4",
// "/masks/Ds0XmIbXdVg5rbVh.mp4",
// "/masks/DsjhztSZvuSlb0aQ.mp4",
// "/masks/EXT8SqD2XiCKtMku.mp4",
// "/masks/fwD3SNlC_nbHZfSD.mp4",
// "/masks/GboDsl7QviQ_xZyr.mp4",
// "/masks/i_F_rv72QCif_vdu.mp4",
// "/masks/IbSY1cb3JtSty0Rb.mp4",
// "/masks/IFf3u7F-AQhvuKwX.mp4",
// "/masks/ITw0tvnCBuRF0jX3.mp4",
// "/masks/ixoKcHjeSQSxjni2.mp4",
// "/masks/IYJldnRloPWaSONT.mp4",
// "/masks/JMYp_rNDBcz8XytW.mp4",
// "/masks/jVJUhmic3cGtAkEl.mp4",
// "/masks/K-4t_iWzSgE0kFTu.mp4",
// "/masks/kCR_Wd103eIzBbNi.mp4",
// "/masks/kYck-h2nAjADqBjJ.mp4",
// "/masks/LBgbpfdD1gWsyHbG.mp4",
// "/masks/LfonVRUrFrd50pJz.mp4",
// "/masks/lrYLvbWx5YvbTgag.mp4",
// "/masks/mask0.mp4",
// "/masks/mask1.mp4",
// "/masks/mask2_2.mp4",
// "/masks/mask2.mp4",
// "/masks/mask5.mp4",
// "/masks/mask6.mp4",
// "/masks/mask7.mp4",
// "/masks/mask8.mp4",
// "/masks/mask9.mp4",
// "/masks/mask10.mp4",
// "/masks/mask11.mp4",
// "/masks/mask12.mp4",
// "/masks/mask13.mp4",
// "/masks/mask14.mp4",
// "/masks/mask15.mp4",
// "/masks/mask16.mp4",
// "/masks/mask17.mp4",
// "/masks/mask18.mp4",
"/masks/mask19.mp4",
// "/masks/mask20.mp4",
"/masks/mask21.mp4",
"/masks/mask22.mp4",
// "/masks/mask23.mp4",
// "/masks/mask24.mp4",
// "/masks/mask25.mp4",
"/masks/mask26.mp4",
"/masks/mask27.mp4",
// "/masks/mask28.mp4",
// "/masks/mask29.mp4",
// "/masks/mask30.mp4",
// "/masks/mask31.mp4",
// "/masks/mask32.mp4",
// "/masks/mask33.mp4",
// "/masks/mask34.mp4",
// "/masks/mask35.mp4",
// "/masks/NcLvdobvFG6NdGbG.mp4",
// "/masks/ND1oNQdxBvgDSEnW.mp4",
// "/masks/new01.mp4",
// "/masks/new02.mp4",
// "/masks/new03.mp4",
// "/masks/njAI29LQysf-YGLN.mp4",
// "/masks/NvgOu8NemOBQLfKW.mp4",
// "/masks/PXCrHqLrXvZ1S8m9.mp4",
// "/masks/R9HLctTUNOVCY8U9.mp4",
// "/masks/RqcMNIobGBChTfrU.mp4",
// "/masks/uqJADw_rofPFjS4b.mp4",
// "/masks/vHJhxHiwggwm8eIU.mp4",
// "/masks/vOs98sKQAZsXLNI7.mp4",
// "/masks/Xp9Q1Fn0mJ55i_s6.mp4",
// "/masks/XUPyIyJNRF9Lo1eC.mp4",
// "/masks/Xz2hSMRES3KdOIHU.mp4",
// "/masks/Y6f9CYbHzDuKOOEV.mp4",
// "/masks/Yhlfv_C2jpSj1pIB.mp4",
// "/masks/ZXw3RNx1Lb6RTj3y.mp4",
]


export interface MaskSourceEntry {
  src: string
  bounce?: boolean
}

export const MASK_PATHS = MASK_PATHS_RELATIVE.map(path => filepathPrefix + path)

export const MASK_SOURCES: MaskSourceEntry[] = MASK_PATHS_RELATIVE.map(path => ({
  src: filepathPrefix + path,
  bounce: false,
}))

