export const CONSTANTS = {
  DEFAULT_CACHE_SIZE: 500,
}

export const Freq530FieldKeys = [
  'time', 'adjustedTime',
  'sin', 'cos', 'sinNormal', 'cosNormal',
  'adjustedSin', 'adjustedCos', 'adjustedSinNormal', 'adjustedCosNormal',
  'low', 'mid', 'high', 'kick', 'snare', 'hihat',
  'vocalLikelihood', 'amplitude', 'rawAmplitude',
  'beatIntensity', 'bps',
  'lowDynamic', 'midDynamic', 'highDynamic',
  'kickDynamic', 'snareDynamic', 'hihatDynamic',
  'amplitudeDynamic', 'rawAmplitudeDynamic',
  'spectralFlux', 'beatTimes', 'lastBeatTime', 'quantizedBands',
  'spectralCentroid', 'chromagram', 'beatPhase', 'frequencyGridMap',
  "lowVelocity",
  "midVelocity",
  "highVelocity",
  "kickVelocity",
  "snareVelocity",
  "hihatVelocity",
  "lowPeakHold",
  "midPeakHold",
  "highPeakHold",
  "kickPeakHold",
  "snarePeakHold",
  "hihatPeakHold",
  "amplitudePeakHold",
  "lowLog",
  "midLog",
  "highLog",
  "lowMidBalance",
  "midHighBalance",
  "onsetStrength",
  "spectrogramData",
] as const