import { VideoSetting } from "./stores/useVideoStore";

export const ALPHA_MASK_PATHS_ALL: VideoSetting[] = [
  { name: "PXCrHqLrXvZ1S8m9.mp4", src: "/masks/group_1/PXCrHqLrXvZ1S8m9.mp4" },
  { name: "Bc8BChM2Nvmd_Xk8.mp4", src: "/masks/group_1/Bc8BChM2Nvmd_Xk8.mp4" },
  { name: "GboDsl7QviQ_xZyr.mp4", src: "/masks/group_1/GboDsl7QviQ_xZyr.mp4" },
  { name: "Y6f9CYbHzDuKOOEV.mp4", src: "/masks/group_1/Y6f9CYbHzDuKOOEV.mp4" },
  { name: "IYJldnRloPWaSONT.mp4", src: "/masks/group_1/IYJldnRloPWaSONT.mp4" },
  { name: "ITw0tvnCBuRF0jX3.mp4", src: "/masks/group_1/ITw0tvnCBuRF0jX3.mp4" },
  { name: "Ds0XmIbXdVg5rbVh.mp4", src: "/masks/group_1/Ds0XmIbXdVg5rbVh.mp4" },
  { name: "vHJhxHiwggwm8eIU.mp4", src: "/masks/group_1/vHJhxHiwggwm8eIU.mp4" },
  { name: "Xz2hSMRES3KdOIHU.mp4", src: "/masks/group_1/Xz2hSMRES3KdOIHU.mp4" },
  { name: "R9HLctTUNOVCY8U9.mp4", src: "/masks/group_1/R9HLctTUNOVCY8U9.mp4" },
  { name: "_w13XKTTxzbJUjAn.mp4", src: "/masks/group_1/_w13XKTTxzbJUjAn.mp4" },
  { name: "K-4t_iWzSgE0kFTu.mp4", src: "/masks/group_1/K-4t_iWzSgE0kFTu.mp4" },
  { name: "Yhlfv_C2jpSj1pIB.mp4", src: "/masks/group_1/Yhlfv_C2jpSj1pIB.mp4" },
  { name: "DsjhztSZvuSlb0aQ.mp4", src: "/masks/group_1/DsjhztSZvuSlb0aQ.mp4" },
  { name: "i_F_rv72QCif_vdu.mp4", src: "/masks/group_1/i_F_rv72QCif_vdu.mp4" },
  { name: "fwD3SNlC_nbHZfSD.mp4", src: "/masks/group_1/fwD3SNlC_nbHZfSD.mp4" },
  { name: "EXT8SqD2XiCKtMku.mp4", src: "/masks/group_1/EXT8SqD2XiCKtMku.mp4" },
  { name: "Xp9Q1Fn0mJ55i_s6.mp4", src: "/masks/group_1/Xp9Q1Fn0mJ55i_s6.mp4" },
  { name: "4InpuBcmZXDImJ6O.mp4", src: "/masks/group_1/4InpuBcmZXDImJ6O.mp4" },
  { name: "JMYp_rNDBcz8XytW.mp4", src: "/masks/group_1/JMYp_rNDBcz8XytW.mp4" },
  { name: "kCR_Wd103eIzBbNi.mp4", src: "/masks/group_1/kCR_Wd103eIzBbNi.mp4" },
  { name: "ixoKcHjeSQSxjni2.mp4", src: "/masks/group_1/ixoKcHjeSQSxjni2.mp4" },
  { name: "uqJADw_rofPFjS4b.mp4", src: "/masks/group_1/uqJADw_rofPFjS4b.mp4" },
  { name: "9MYXnN7RhURggYrR.mp4", src: "/masks/group_1/9MYXnN7RhURggYrR.mp4" },
  { name: "IFf3u7F-AQhvuKwX.mp4", src: "/masks/group_1/IFf3u7F-AQhvuKwX.mp4" },
  { name: "1t_J8CtMxSy0FV_B.mp4", src: "/masks/group_1/1t_J8CtMxSy0FV_B.mp4" },
  { name: "LBgbpfdD1gWsyHbG.mp4", src: "/masks/group_1/LBgbpfdD1gWsyHbG.mp4" },
  { name: "njAI29LQysf-YGLN.mp4", src: "/masks/group_1/njAI29LQysf-YGLN.mp4" },
  { name: "LfonVRUrFrd50pJz.mp4", src: "/masks/group_1/LfonVRUrFrd50pJz.mp4" },
  { name: "IbSY1cb3JtSty0Rb.mp4", src: "/masks/group_1/IbSY1cb3JtSty0Rb.mp4" },
  { name: "XUPyIyJNRF9Lo1eC.mp4", src: "/masks/group_1/XUPyIyJNRF9Lo1eC.mp4" },
  { name: "lrYLvbWx5YvbTgag.mp4", src: "/masks/group_1/lrYLvbWx5YvbTgag.mp4" },
  { name: "vOs98sKQAZsXLNI7.mp4", src: "/masks/group_1/vOs98sKQAZsXLNI7.mp4" },
  { name: "RqcMNIobGBChTfrU.mp4", src: "/masks/group_1/RqcMNIobGBChTfrU.mp4" },
  { name: "jVJUhmic3cGtAkEl.mp4", src: "/masks/group_1/jVJUhmic3cGtAkEl.mp4" },
  { name: "_NHt0ZDTUk1pDKfO.mp4", src: "/masks/group_1/_NHt0ZDTUk1pDKfO.mp4" },
  { name: "kYck-h2nAjADqBjJ.mp4", src: "/masks/group_1/kYck-h2nAjADqBjJ.mp4" },
  { name: "ND1oNQdxBvgDSEnW.mp4", src: "/masks/group_1/ND1oNQdxBvgDSEnW.mp4" },
  { name: "NvgOu8NemOBQLfKW.mp4", src: "/masks/group_1/NvgOu8NemOBQLfKW.mp4" },
  { name: "NcLvdobvFG6NdGbG.mp4", src: "/masks/group_1/NcLvdobvFG6NdGbG.mp4" },
  { name: "12_enHs-dsfu53QB.mp4", src: "/masks/group_1/12_enHs-dsfu53QB.mp4" },
  { name: "ZXw3RNx1Lb6RTj3y.mp4", src: "/masks/group_1/ZXw3RNx1Lb6RTj3y.mp4" },
  { name: "bvU1yaZwsd0V9DRO.mp4", src: "/masks/group_1/bvU1yaZwsd0V9DRO.mp4" },
  { name: "3mTgvzaoas-K41IU.mp4", src: "/masks/group_1/3mTgvzaoas-K41IU.mp4" },
  { name: "29gy33VGl5dTXDDu.mp4", src: "/masks/group_1/29gy33VGl5dTXDDu.mp4" },
  { name: "new03.mp4",            src: "/masks/group_1/new03.mp4" },
  { name: "new02.mp4",            src: "/masks/group_1/new02.mp4" },
  { name: "new01.mp4",            src: "/masks/group_1/new01.mp4" },
  { name: "mask35.mp4",           src: "/masks/group_1/mask35.mp4" },
  { name: "mask34.mp4",           src: "/masks/group_1/mask34.mp4" },
  { name: "mask33.mp4",           src: "/masks/group_1/mask33.mp4" },
  { name: "mask32.mp4",           src: "/masks/group_1/mask32.mp4" },
  { name: "mask31.mp4",           src: "/masks/group_1/mask31.mp4" },
  { name: "mask30.mp4",           src: "/masks/group_1/mask30.mp4" },
  { name: "mask29.mp4",           src: "/masks/group_1/mask29.mp4" },
  { name: "mask28.mp4",           src: "/masks/group_1/mask28.mp4" },
  { name: "mask27.mp4",           src: "/masks/group_1/mask27.mp4" },
  { name: "mask26.mp4",           src: "/masks/group_1/mask26.mp4" },
  { name: "mask25.mp4",           src: "/masks/group_1/mask25.mp4" },
  { name: "mask24.mp4",           src: "/masks/group_1/mask24.mp4" },
  { name: "mask23.mp4",           src: "/masks/group_1/mask23.mp4" },
  { name: "mask22.mp4",           src: "/masks/group_1/mask22.mp4" },
  { name: "mask21.mp4",           src: "/masks/group_1/mask21.mp4" },
  { name: "mask20.mp4",           src: "/masks/group_1/mask20.mp4" },
  { name: "mask19.mp4",           src: "/masks/group_1/mask19.mp4" },
  { name: "mask18.mp4",           src: "/masks/group_1/mask18.mp4" },
  { name: "mask17.mp4",           src: "/masks/group_1/mask17.mp4" },
  { name: "mask16.mp4",           src: "/masks/group_1/mask16.mp4" },
  { name: "mask15.mp4",           src: "/masks/group_1/mask15.mp4" },
  { name: "mask14.mp4",           src: "/masks/group_1/mask14.mp4" },
  { name: "mask13.mp4",           src: "/masks/group_1/mask13.mp4" },
  { name: "mask12.mp4",           src: "/masks/group_1/mask12.mp4" },
  { name: "mask11.mp4",           src: "/masks/group_1/mask11.mp4" },
  { name: "mask10.mp4",           src: "/masks/group_1/mask10.mp4" },
  { name: "mask9.mp4",            src: "/masks/group_1/mask9.mp4" },
  { name: "mask8.mp4",            src: "/masks/group_1/mask8.mp4" },
  { name: "mask7.mp4",            src: "/masks/group_1/mask7.mp4" },
  { name: "mask6.mp4",            src: "/masks/group_1/mask6.mp4" },
  { name: "mask5.mp4",            src: "/masks/group_1/mask5.mp4" },
  { name: "mask0.mp4",            src: "/masks/group_1/mask0.mp4" },
  { name: "mask1.mp4",            src: "/masks/group_1/mask1.mp4" },
  { name: "mask2_2.mp4",          src: "/masks/group_1/mask2_2.mp4" },
  { name: "mask2.mp4",            src: "/masks/group_1/mask2.mp4" },
]
export const ALPHA_MASK_PATHS = [
  ALPHA_MASK_PATHS_ALL[2],
  ALPHA_MASK_PATHS_ALL[5],
]

export const VIDEO_PATHS_ALL: VideoSetting[] = [
{name: "zcK3rihY3BcDpBtA.mp4", src: "/videos/group_1/zcK3rihY3BcDpBtA.mp4"},
{name: "yHI3qPVuno7eBVW2.mp4", src: "/videos/group_1/yHI3qPVuno7eBVW2.mp4"},
{name: "xO0bI3kw5wIj1e7e.mp4", src: "/videos/group_1/xO0bI3kw5wIj1e7e.mp4"},
{name: "xL3MJE0NmIR0Jkhx.mp4", src: "/videos/group_1/xL3MJE0NmIR0Jkhx.mp4"},
{name: "sXHJMpzbF7Vxa9BH.mp4", src: "/videos/group_1/sXHJMpzbF7Vxa9BH.mp4"},
{name: "q2TViYgCqqJZ3Zto.mp4", src: "/videos/group_1/q2TViYgCqqJZ3Zto.mp4"},
{name: "oACo-KJIzd7F00Xv.mp4", src: "/videos/group_1/oACo-KJIzd7F00Xv.mp4"},
{name: "mzKYyGSGqNfiKhix.mp4", src: "/videos/group_1/mzKYyGSGqNfiKhix.mp4"},
{name: "h2S_ZTpRejhudjrB.mp4", src: "/videos/group_1/h2S_ZTpRejhudjrB.mp4"},
{name: "gyVop7DX9A_cT6-h.mp4", src: "/videos/group_1/gyVop7DX9A_cT6-h.mp4"},
{name: "gRl2ZYH0tglzVYZ7.mp4", src: "/videos/group_1/gRl2ZYH0tglzVYZ7.mp4"},
{name: "eKRnec7g-bp1z1gp.mp4", src: "/videos/group_1/eKRnec7g-bp1z1gp.mp4"},
{name: "Wdx0WPG4riOnHPzJ.mp4", src: "/videos/group_1/Wdx0WPG4riOnHPzJ.mp4"},
{name: "WXUFYVWLXTE8d_f8.mp4", src: "/videos/group_1/WXUFYVWLXTE8d_f8.mp4"},
{name: "VvTaml2CBFKTO5w4.mp4", src: "/videos/group_1/VvTaml2CBFKTO5w4.mp4"},
{name: "SagZTALgNGJr6DtD.mp4", src: "/videos/group_1/SagZTALgNGJr6DtD.mp4"},
{name: "RHjlUnYVOZaJuM88.mp4", src: "/videos/group_1/RHjlUnYVOZaJuM88.mp4"},
{name: "GPb-uIxXcAAWQcB.mp4",  src: "/videos/group_1/GPb-uIxXcAAWQcB.mp4"},
{name: "FoZuBgxxBUkNu43l.mp4", src: "/videos/group_1/FoZuBgxxBUkNu43l.mp4"},
{name: "E2jrpnuRqWNDn_XT.mp4", src: "/videos/group_1/E2jrpnuRqWNDn_XT.mp4"},
{name: "D1M6N1ktcCEGwwXZ.mp4", src: "/videos/group_1/D1M6N1ktcCEGwwXZ.mp4"},
{name: "4xLLjHaCCODWel7T.mp4", src: "/videos/group_1/4xLLjHaCCODWel7T.mp4"},
{name: "2Z75IH7UF4IHObBD.mp4", src: "/videos/group_1/2Z75IH7UF4IHObBD.mp4"},
{name: "1Oh8K3CXAG1s0hmh.mp4", src: "/videos/group_1/1Oh8K3CXAG1s0hmh.mp4"},
{name: "0YEeB5CHuW-S0koX.mp4", src: "/videos/group_1/0YEeB5CHuW-S0koX.mp4"},
]
export const VIDEO_PATHS = [
  VIDEO_PATHS_ALL[2],
  VIDEO_PATHS_ALL[5],
]